Update to v4.0.1

diff --git a/xed/debian/postinst b/xed/debian/postinst
--- a/xed/debian/postinst
+++ b/xed/debian/postinst
@@ -4,14 +4,15 @@ set -e
 case "$1" in
     configure)
         echo "Running post-installation script"
+        ORIGINAL_USER=${SUDO_USER:-$(logname)}
+        if [ -z "$ORIGINAL_USER" ]; then
+            echo "Unable to determine the non-root user to execute dconf commands."
+            exit 1
+        fi
+        PLUGINS="$(sudo -u "$ORIGINAL_USER" dconf read /org/x/editor/plugins/active-plugins)"
+        echo $PLUGINS >/var/log/editortoix-postinst.log 2>&1
+
         if [ -z "$2" ]; then
-            ORIGINAL_USER=${SUDO_USER:-$(logname)}
-            if [ -z "$ORIGINAL_USER" ]; then
-                echo "Unable to determine the non-root user to execute dconf commands."
-                exit 1
-            fi
-            PLUGINS="$(sudo -u "$ORIGINAL_USER" dconf read /org/x/editor/plugins/active-plugins)"
-            echo $PLUGINS >/var/log/editortoix-postinst.log 2>&1
             if [ -n "$PLUGINS" ]; then
                 case "$PLUGINS" in
                     *toix_*)
@@ -30,6 +31,11 @@ case "$1" in
                         ;;
                 esac
             fi
+        elif [ "$2" = "4.0.1" ]; then
+            rm -rf "/usr/lib/x86_64-linux-gnu/xed/plugins/toix_trimright"
+            PLUGINS="$(echo "$PLUGINS" | sed 's/trimright/trimtrailing/')"
+            echo $PLUGINS >>/var/log/editortoix-postinst.log 2>&1
+            sudo -u "$ORIGINAL_USER" dconf write /org/x/editor/plugins/active-plugins "$PLUGINS"
         fi
         ;;
     *)
